package com.spider.entity;

// Generated 2015-7-21 10:41:12 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.StringUtils;

/**
 * HhadOdds generated by hbm2java
 */
@Entity
@Table(name = "had_odds")
public class HadOdds implements java.io.Serializable {

    private static final long serialVersionUID = -5234128970474345447L;

    private Long id;

    private String gamingCompany = "";

    private String oddsA = "";

    private String oddsD = "";

    private String oddsH = "";

    private Date updateTime = new Date();

    private String oddsUpdateTime = "";

    private String state = "";

    private String score = "";

    private Long win310Id;

    private String durationTime = "";

    private Integer homeRedCard = 0;

    private Integer awayRedCard = 0;

    private Integer europeId;

    @Column(name = "EUROPE_ID")
    public Integer getEuropeId() {

        return europeId;
    }

    public void setEuropeId(Integer europeId) {

        this.europeId = europeId;
    }

    @Column(name = "HOME_RED_CARD")
    public Integer getHomeRedCard() {

        return homeRedCard;
    }

    public void setHomeRedCard(Integer homeRedCard) {

        this.homeRedCard = homeRedCard;
    }

    @Column(name = "AWAY_RED_CARD")
    public Integer getAwayRedCard() {

        return awayRedCard;
    }

    public void setAwayRedCard(Integer awayRedCard) {

        this.awayRedCard = awayRedCard;
    }

    public void setDurationTime(String durationTime) {

        if (StringUtils.isBlank(durationTime)) {
            this.durationTime = "";
            return;
        }
        this.durationTime = durationTime;

    }

    @Column(name = "DURATION_TIME", length = 5)
    public String getDurationTime() {

        return durationTime;
    }

    @Column(name = "WIN310_ID", nullable = false)
    public Long getWin310Id() {

        return win310Id;
    }

    public void setWin310Id(Long win310Id) {

        this.win310Id = win310Id;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {

        return this.id;
    }

    public void setId(Long id) {

        this.id = id;
    }

    @Column(name = "GAMING_COMPANY", nullable = false, length = 50)
    public String getGamingCompany() {

        return this.gamingCompany;
    }

    public void setGamingCompany(String gamingCompany) {

        this.gamingCompany = gamingCompany;
    }

    @Column(name = "ODDS_A", nullable = false, length = 5)
    public String getOddsA() {

        return this.oddsA;
    }

    public void setOddsA(String oddsA) {

        this.oddsA = oddsA;
    }

    @Column(name = "ODDS_D", nullable = false, length = 10)
    public String getOddsD() {

        return this.oddsD;
    }

    public void setOddsD(String oddsD) {

        this.oddsD = oddsD;
    }

    @Column(name = "ODDS_H", nullable = false, length = 5)
    public String getOddsH() {

        return this.oddsH;
    }

    public void setOddsH(String oddsH) {

        this.oddsH = oddsH;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 19)
    public Date getUpdateTime() {

        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {

        this.updateTime = updateTime;
    }

    @Column(name = "ODDS_UPDATE_TIME", nullable = false, length = 20)
    public String getOddsUpdateTime() {

        return this.oddsUpdateTime;
    }

    public void setOddsUpdateTime(String oddsUpdateTime) {

        this.oddsUpdateTime = oddsUpdateTime;
    }

    @Column(name = "STATE", nullable = false, length = 2)
    public String getState() {

        return state;
    }

    public void setState(String state) {

        this.state = state;
    }

    @Column(name = "SCORE", nullable = false, length = 2)
    public String getScore() {

        return score;
    }

    public void setScore(String score) {

        this.score = score;
    }

    public HadOdds from(HadOddsHistory hadOddsHistory) {

        this.win310Id = hadOddsHistory.getWin310Id();
        this.gamingCompany = hadOddsHistory.getGamingCompany();
        this.oddsA = hadOddsHistory.getOddsA();
        this.oddsD = hadOddsHistory.getOddsD();
        this.oddsH = hadOddsHistory.getOddsH();
        this.updateTime = hadOddsHistory.getUpdateTime();
        this.oddsUpdateTime = hadOddsHistory.getOddsUpdateTime();
        this.state = hadOddsHistory.getState();
        this.score = hadOddsHistory.getScore();
        this.durationTime = hadOddsHistory.getDurationTime();
        this.homeRedCard = hadOddsHistory.getHomeRedCard();
        this.awayRedCard = hadOddsHistory.getAwayRedCard();
        this.europeId = hadOddsHistory.getEuropeId();
        return this;
    }

    @Override
    public boolean equals(Object o) {

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        HadOdds hadOdds = (HadOdds) o;

        if (gamingCompany != null ? !gamingCompany.equals(hadOdds.gamingCompany) : hadOdds.gamingCompany != null)
            return false;
        if (oddsA != null ? !oddsA.equals(hadOdds.oddsA) : hadOdds.oddsA != null) return false;
        if (oddsD != null ? !oddsD.equals(hadOdds.oddsD) : hadOdds.oddsD != null) return false;
        if (oddsH != null ? !oddsH.equals(hadOdds.oddsH) : hadOdds.oddsH != null) return false;
        if (oddsUpdateTime != null ? !oddsUpdateTime.equals(hadOdds.oddsUpdateTime) : hadOdds.oddsUpdateTime != null)
            return false;
        if (state != null ? !state.equals(hadOdds.state) : hadOdds.state != null) return false;
        if (score != null ? !score.equals(hadOdds.score) : hadOdds.score != null) return false;
        if (win310Id != null ? !win310Id.equals(hadOdds.win310Id) : hadOdds.win310Id != null) return false;
        if (durationTime != null ? !durationTime.equals(hadOdds.durationTime) : hadOdds.durationTime != null)
            return false;
        if (homeRedCard != null ? !homeRedCard.equals(hadOdds.homeRedCard) : hadOdds.homeRedCard != null) return false;
        if (europeId != null ? !europeId.equals(hadOdds.europeId) : hadOdds.europeId != null) return false;
        return !(awayRedCard != null ? !awayRedCard.equals(hadOdds.awayRedCard) : hadOdds.awayRedCard != null);

    }

    @Override
    public int hashCode() {

        int result = gamingCompany != null ? gamingCompany.hashCode() : 0;
        result = 31 * result + (oddsA != null ? oddsA.hashCode() : 0);
        result = 31 * result + (oddsD != null ? oddsD.hashCode() : 0);
        result = 31 * result + (oddsH != null ? oddsH.hashCode() : 0);
        result = 31 * result + (oddsUpdateTime != null ? oddsUpdateTime.hashCode() : 0);
        result = 31 * result + (state != null ? state.hashCode() : 0);
        result = 31 * result + (score != null ? score.hashCode() : 0);
        result = 31 * result + (win310Id != null ? win310Id.hashCode() : 0);
        result = 31 * result + (durationTime != null ? durationTime.hashCode() : 0);
        result = 31 * result + (homeRedCard != null ? homeRedCard.hashCode() : 0);
        result = 31 * result + (awayRedCard != null ? awayRedCard.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {

        return "HadOdds{" +
                "id=" + id +
                ", gamingCompany='" + gamingCompany + '\'' +
                ", oddsA='" + oddsA + '\'' +
                ", oddsD='" + oddsD + '\'' +
                ", oddsH='" + oddsH + '\'' +
                ", updateTime=" + updateTime +
                ", oddsUpdateTime='" + oddsUpdateTime + '\'' +
                ", state='" + state + '\'' +
                ", score='" + score + '\'' +
                ", win310Id=" + win310Id +
                ", durationTime='" + durationTime + '\'' +
                ", homeRedCard=" + homeRedCard +
                ", awayRedCard=" + awayRedCard +
                ", europeId=" + europeId +
                '}';
    }
}
