package com.spider.entity;

// Generated 2015-7-21 10:41:12 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.spider.domain.GamingCompany;
import org.apache.commons.lang3.StringUtils;

/**
 * HadOdds generated by hbm2java
 */
@Entity
@Table(name = "hhad_odds_history")
public class HdcOddsHistory implements java.io.Serializable {

    private static final long serialVersionUID = -5234128970474345447L;

    private Long id;

    private String gamingCompany = "";

    private String oddsOne = "";

    private String handicapLine = "";

    private String oddsTwo = "";

    private Date updateTime = new Date();

    private String oddsUpdateTime = "";

    private String state = "";

    private String score = "";

    private Long win310Id;

    private String durationTime = "";

    private Integer homeRedCard = 0;

    private Integer awayRedCard = 0;

    private Integer europeId;

    @Column(name = "EUROPE_ID")
    public Integer getEuropeId() {

        return europeId;
    }

    public void setEuropeId(Integer europeId) {

        this.europeId = europeId;
    }

    @Column(name = "HOME_RED_CARD")
    public Integer getHomeRedCard() {

        return homeRedCard;
    }

    public void setHomeRedCard(Integer homeRedCard) {

        this.homeRedCard = homeRedCard;
    }

    @Column(name = "AWAY_RED_CARD")
    public Integer getAwayRedCard() {

        return awayRedCard;
    }

    public void setAwayRedCard(Integer awayRedCard) {

        this.awayRedCard = awayRedCard;
    }

    public void setDurationTime(String durationTime) {

        if (StringUtils.isBlank(durationTime)) {
            this.durationTime = "";
            return;
        }
        this.durationTime = durationTime;

    }

    @Column(name = "DURATION_TIME", length = 5)
    public String getDurationTime() {

        return durationTime;
    }

    public HdcOddsHistory() {

    }

    public HdcOddsHistory(HdcOdds hdcOdds) {

        this.gamingCompany = hdcOdds.getGamingCompany();
        this.oddsOne = hdcOdds.getOddsOne();
        this.handicapLine = hdcOdds.getHandicapLine();
        this.oddsTwo = hdcOdds.getOddsTwo();
        this.updateTime = hdcOdds.getUpdateTime();
        this.oddsUpdateTime = hdcOdds.getOddsUpdateTime();
        this.state = hdcOdds.getState();
        this.score = hdcOdds.getScore();
        this.win310Id = hdcOdds.getWin310Id();
        this.durationTime = hdcOdds.getDurationTime();
        this.homeRedCard = hdcOdds.getHomeRedCard();
        this.awayRedCard = hdcOdds.getAwayRedCard();
        this.europeId = hdcOdds.getEuropeId();
    }

    @Column(name = "WIN310_ID", nullable = false)
    public Long getWin310Id() {

        return win310Id;
    }

    public void setWin310Id(Long win310Id) {

        this.win310Id = win310Id;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {

        return this.id;
    }

    public void setId(Long id) {

        this.id = id;
    }

    @Column(name = "GAMING_COMPANY", nullable = false, length = 50)
    public String getGamingCompany() {

        return this.gamingCompany;
    }

    public void setGamingCompany(String gamingCompany) {

        this.gamingCompany = gamingCompany;
    }

    @Column(name = "ODDS_ONE", nullable = false, length = 5)
    public String getOddsOne() {

        return this.oddsOne;
    }

    public void setOddsOne(String oddsOne) {

        this.oddsOne = oddsOne;
    }

    @Column(name = "HANDICAP_LINE", nullable = false, length = 10)
    public String getHandicapLine() {

        return this.handicapLine;
    }

    public void setHandicapLine(String handicapLine) {

        this.handicapLine = handicapLine;
    }

    @Column(name = "ODDS_TWO", nullable = false, length = 5)
    public String getOddsTwo() {

        return this.oddsTwo;
    }

    public void setOddsTwo(String oddsTwo) {

        this.oddsTwo = oddsTwo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 19)
    public Date getUpdateTime() {

        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {

        this.updateTime = updateTime;
    }

    @Column(name = "ODDS_UPDATE_TIME", nullable = false, length = 20)
    public String getOddsUpdateTime() {

        return this.oddsUpdateTime;
    }

    public void setOddsUpdateTime(String oddsUpdateTime) {

        this.oddsUpdateTime = oddsUpdateTime;
    }

    @Column(name = "STATE", nullable = false, length = 2)
    public String getState() {

        return state;
    }

    public void setState(String state) {

        this.state = state;
    }

    @Column(name = "SCORE", nullable = false, length = 2)
    public String getScore() {

        return score;
    }

    public void setScore(String score) {

        this.score = score;
    }

    @Override
    public String toString() {

        return "HdcOddsHistory{" +
                "awayRedCard=" + awayRedCard +
                ", homeRedCard=" + homeRedCard +
                ", durationTime='" + durationTime + '\'' +
                ", win310Id=" + win310Id +
                ", score='" + score + '\'' +
                ", state='" + state + '\'' +
                ", oddsUpdateTime='" + oddsUpdateTime + '\'' +
                ", updateTime=" + updateTime +
                ", oddsTwo='" + oddsTwo + '\'' +
                ", handicapLine='" + handicapLine + '\'' +
                ", oddsOne='" + oddsOne + '\'' +
                ", gamingCompany='" + gamingCompany + '\'' +
                ", id=" + id +
                ", europeId=" + europeId +
                '}';
    }
}
