package com.spider.entity;

// Generated 2015-7-21 10:41:12 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.spider.domain.GamingCompany;
import org.apache.commons.lang3.StringUtils;

/**
 * HhadOdds generated by hbm2java
 */
@Entity
@Table(name = "highlow_odds_history")
public class HiloOddsHistory implements java.io.Serializable {

    private static final long serialVersionUID = -5234128970474345447L;

    private Long id;

    private String gamingCompany = "";

    private String oddsHigh = "";

    private String oddsLow = "";

    private String handicapLine = "";

    private Date updateTime = new Date();

    private String oddsUpdateTime = "";

    private String state = "";

    private String score = "";

    private Long win310Id;

    private String durationTime = "";

    private Integer homeRedCard = 0;

    private Integer awayRedCard = 0;
    private Integer europeId;

    @Column(name = "EUROPE_ID")
    public Integer getEuropeId() {

        return europeId;
    }

    public void setEuropeId(Integer europeId) {

        this.europeId = europeId;
    }

    @Column(name = "HOME_RED_CARD")
    public Integer getHomeRedCard() {

        return homeRedCard;
    }

    public void setHomeRedCard(Integer homeRedCard) {

        this.homeRedCard = homeRedCard;
    }

    @Column(name = "AWAY_RED_CARD")
    public Integer getAwayRedCard() {

        return awayRedCard;
    }

    public void setAwayRedCard(Integer awayRedCard) {

        this.awayRedCard = awayRedCard;
    }

    public void setDurationTime(String durationTime) {

        if (StringUtils.isBlank(durationTime)) {
            this.durationTime = "";
            return;
        }
        this.durationTime = durationTime;

    }

    @Column(name = "DURATION_TIME", length = 5)
    public String getDurationTime() {

        return durationTime;
    }

    public HiloOddsHistory() {

    }

    public HiloOddsHistory(HiloOdds hiloOdds) {

        this.gamingCompany = hiloOdds.getGamingCompany();
        this.oddsHigh = hiloOdds.getOddsHigh();
        this.oddsLow = hiloOdds.getOddsLow();
        this.handicapLine = hiloOdds.getHandicapLine();
        this.updateTime = hiloOdds.getUpdateTime();
        this.oddsUpdateTime = hiloOdds.getOddsUpdateTime();
        this.state = hiloOdds.getState();
        this.score = hiloOdds.getScore();
        this.win310Id = hiloOdds.getWin310Id();
        this.durationTime = hiloOdds.getDurationTime();
        this.homeRedCard = hiloOdds.getHomeRedCard();
        this.awayRedCard = hiloOdds.getAwayRedCard();
        this.europeId = hiloOdds.getEuropeId();
    }

    @Column(name = "WIN310_ID", nullable = false)
    public Long getWin310Id() {

        return win310Id;
    }

    public void setWin310Id(Long win310Id) {

        this.win310Id = win310Id;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {

        return this.id;
    }

    public void setId(Long id) {

        this.id = id;
    }

    @Column(name = "GAMING_COMPANY", nullable = false, length = 50)
    public String getGamingCompany() {

        return this.gamingCompany;
    }

    public void setGamingCompany(String gamingCompany) {

        this.gamingCompany = gamingCompany;
    }

    @Column(name = "ODDS_HIGH", nullable = false, length = 5)
    public String getOddsHigh() {

        return this.oddsHigh;
    }

    public void setOddsHigh(String oddsHigh) {

        this.oddsHigh = oddsHigh;
    }

    @Column(name = "ODDS_LOW", nullable = false, length = 5)
    public String getOddsLow() {

        return this.oddsLow;
    }

    public void setOddsLow(String oddsLow) {

        this.oddsLow = oddsLow;
    }

    @Column(name = "HANDICAP_LINE", nullable = false, length = 5)
    public String getHandicapLine() {

        return this.handicapLine;
    }

    public void setHandicapLine(String handicapLine) {

        this.handicapLine = handicapLine;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 19)
    public Date getUpdateTime() {

        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {

        this.updateTime = updateTime;
    }

    @Column(name = "ODDS_UPDATE_TIME", nullable = false, length = 20)
    public String getOddsUpdateTime() {

        return this.oddsUpdateTime;
    }

    public void setOddsUpdateTime(String oddsUpdateTime) {

        this.oddsUpdateTime = oddsUpdateTime;
    }

    @Column(name = "STATE", nullable = false, length = 2)
    public String getState() {

        return state;
    }

    public void setState(String state) {

        this.state = state;
    }

    @Column(name = "SCORE", nullable = false, length = 2)
    public String getScore() {

        return score;
    }

    public void setScore(String score) {

        this.score = score;
    }

    @Override
    public String toString() {

        return "HiloOddsHistory{" +
                "id=" + id +
                ", gamingCompany='" + gamingCompany + '\'' +
                ", oddsHigh='" + oddsHigh + '\'' +
                ", oddsLow='" + oddsLow + '\'' +
                ", handicapLine='" + handicapLine + '\'' +
                ", updateTime=" + updateTime +
                ", oddsUpdateTime='" + oddsUpdateTime + '\'' +
                ", state='" + state + '\'' +
                ", score='" + score + '\'' +
                ", win310Id=" + win310Id +
                ", durationTime='" + durationTime + '\'' +
                ", homeRedCard=" + homeRedCard +
                ", awayRedCard=" + awayRedCard +
                ", europeId=" + europeId +
                '}';
    }
}
