package com.spider.entity;

// Generated 2015-7-14 17:26:36 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TCrawlerPinnaclesports generated by hbm2java
 */
@Entity
@Table(name = "t_crawler_pinnaclesports")
public class TCrawlerPinnaclesports implements java.io.Serializable {

    private static final long serialVersionUID = -4311110977329713021L;

    private Long id;

    private String matchs;

    private String startDate;

    private String startTime;

    private String homeTeam;

    private String visitionTeam;

    private String handicap1;

    private String handicap2;

    private String win;

    private String fail;

    private String draw;

    private String total1;

    private String total2;

    private Date updateTime = new Date();

    public TCrawlerPinnaclesports() {

    }

    public TCrawlerPinnaclesports(String matchs, String startDate, String startTime, String homeTeam, String visitionTeam, String handicap1, String handicap2, String win, String fail, String draw,
            String total1, String total2, Date updateTime) {

        this.matchs = matchs;
        this.startDate = startDate;
        this.startTime = startTime;
        this.homeTeam = homeTeam;
        this.visitionTeam = visitionTeam;
        this.handicap1 = handicap1;
        this.handicap2 = handicap2;
        this.win = win;
        this.fail = fail;
        this.draw = draw;
        this.total1 = total1;
        this.total2 = total2;
        this.updateTime = updateTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {

        return this.id;
    }

    public void setId(Long id) {

        this.id = id;
    }

    @Column(name = "MATCHS", nullable = false, length = 100)
    public String getMatchs() {

        return this.matchs;
    }

    public void setMatchs(String matchs) {

        this.matchs = matchs;
    }

    @Column(name = "START_DATE", nullable = false, length = 20)
    public String getStartDate() {

        return this.startDate;
    }

    public void setStartDate(String startDate) {

        this.startDate = startDate;
    }

    @Column(name = "START_TIME", nullable = false, length = 20)
    public String getStartTime() {

        return this.startTime;
    }

    public void setStartTime(String startTime) {

        this.startTime = startTime;
    }

    @Column(name = "HOME_TEAM", nullable = false, length = 50)
    public String getHomeTeam() {

        return this.homeTeam;
    }

    public void setHomeTeam(String homeTeam) {

        this.homeTeam = homeTeam;
    }

    @Column(name = "VISITION_TEAM", nullable = false, length = 50)
    public String getVisitionTeam() {

        return this.visitionTeam;
    }

    public void setVisitionTeam(String visitionTeam) {

        this.visitionTeam = visitionTeam;
    }

    @Column(name = "HANDICAP_1", nullable = false, length = 30)
    public String getHandicap1() {

        return this.handicap1;
    }

    public void setHandicap1(String handicap1) {

        this.handicap1 = handicap1;
    }

    @Column(name = "HANDICAP_2", nullable = false, length = 30)
    public String getHandicap2() {

        return this.handicap2;
    }

    public void setHandicap2(String handicap2) {

        this.handicap2 = handicap2;
    }

    @Column(name = "WIN", nullable = false, length = 10)
    public String getWin() {

        return this.win;
    }

    public void setWin(String win) {

        this.win = win;
    }

    @Column(name = "FAIL", nullable = false, length = 10)
    public String getFail() {

        return this.fail;
    }

    public void setFail(String fail) {

        this.fail = fail;
    }

    @Column(name = "DRAW", nullable = false, length = 10)
    public String getDraw() {

        return this.draw;
    }

    public void setDraw(String draw) {

        this.draw = draw;
    }

    @Column(name = "TOTAL_1", nullable = false, length = 50)
    public String getTotal1() {

        return this.total1;
    }

    public void setTotal1(String total1) {

        this.total1 = total1;
    }

    @Column(name = "TOTAL_2", nullable = false, length = 50)
    public String getTotal2() {

        return this.total2;
    }

    public void setTotal2(String total2) {

        this.total2 = total2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", nullable = false, length = 19)
    public Date getUpdateTime() {

        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {

        this.updateTime = updateTime;
    }

}
